name: contact_picker_web
version: 5.0.0+1
description: Use Chromes contact picker to chose phone numbers and email addresses from contacts of the users address book
homepage: https://github.com/DRSchlaubi/contact_picker/tree/feature/web/contact_picker_web

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterContactPickerPlugin
        fileName: contact_picker_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
  contact_picker_platform_interface:
    path: ../contact_picker_platform_interface

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"
